name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3  # Use the latest version (v3) for checkout

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci  # Use npm ci (cache busting) for CI builds

      - name: Build with Webpack
        run: npm run build  # Assuming you have a "build" script in package.json

      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v3  # Upload build artifacts for potential inspection
        with:
          name: build-artifacts  # Customize the artifact name
          path: dist/  # Assuming your build output goes into the "dist" folder (adjust accordingly)

